// Code generated by protoc-gen-goyuki, but your can (must) modify it.
// source: pb/strings.proto

package strings

import (
	"github.com/ra9form/yuki/transport"
	desc "github.com/utrack/yuki/integration/binding_with_body_and_response/pb"
)

type StringsImplementation struct {
	desc.UnimplementedStringsServer
}

func NewStrings() *StringsImplementation {
	return &StringsImplementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *StringsImplementation) GetDescription() transport.ServiceDesc {
	return desc.NewStringsServiceDesc(i)
}
