run:
  skip-dirs:
    - vendor
    - pb
    - static
  modules-download-mode: vendor

linters:
  enable-all: true

issues:
  # Restricts maximum count of issues to display with the same text, and show all instead.
  max-same-issues: 0
  max-issues-per-linter: 0

linters-settings:
  tagliatelle:
    # Check the struck tag name case.
    case:
      # Use the struct field name to check the name of the struct tag.
      # Default: false
      use-field-name: true
      rules:
        json: snake
