// Code generated by protoc-gen-goyuki, but your can (must) modify it.
// source: strings.proto

package strings

import (
	"context"
	"strings"
	"time"

	desc "github.com/utrack/yuki/integration/client_cancel_request/pkg/strings"
)

func (i *StringsImplementation) ToUpper(ctx context.Context, req *desc.String) (*desc.String, error) {
	time.Sleep(100 * time.Millisecond)
	return &desc.String{Str: strings.ToUpper(req.Str)}, nil
}
