// Code generated by protoc-gen-goyuki, but you can (must) modify it.
// source: pb/strings.proto

package strings

import (
	"context"
	"strings"

	desc "github.com/utrack/yuki/integration/additional_bindings/pb"
)

func (i *StringsImplementation) ToUpper(ctx context.Context, req *desc.String) (*desc.String, error) {
	resp := &desc.String{Str: strings.ToUpper(req.GetStr())}
	return resp, nil
}
