// Code generated by protoc-gen-goyuki, but you can (must) modify it.
// source: strings.proto

package strings

import (
	"github.com/ra9form/yuki/transport"
	desc "github.com/utrack/yuki/integration/go_package_separate_impl_exists/pkg/strings"
)

type StringsImplementation struct {
	desc.UnimplementedStringsServer
}

// NewStrings create new StringsImplementation
func NewStrings() *StringsImplementation {
	return &StringsImplementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *StringsImplementation) GetDescription() transport.ServiceDesc {
	return desc.NewStringsServiceDesc(i)
}
