// Code generated by protoc-gen-goyuki, but your can (must) modify it.
// source: pb/strings.proto

package strings

import (
	"context"
	"strings"

	desc "github.com/utrack/yuki/integration/impl_file_name_tmpl/pb"
)

func (i *StringsImplementation) ToUpper(ctx context.Context, req *desc.String) (*desc.String, error) {
	return &desc.String{Str: strings.ToUpper(req.Str)}, nil
}
